json.label @post.label
json.title @post.title
json.meta_description @post.meta_description
json.meta_keywords @post.meta_keywords
json.notes @post.notes
json.is_published @post.is_published
json.date_published @post.date_published
json.created_at @post.created_at
json.active @post.active
json.themes @post.themes